version: '3.4'

services:
  server:
    container_name: server
    environment:
        MSSQL_SA_PASSWORD: "Admin@12345"        
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433" 

  olp:
    container_name: olp
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=server;Database=OnlineLearningPlatformDB;User Id=sa;Password=Admin@12345;Encrypt=false"
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - server
    restart: always

    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro